definitions:
  models.OtpRequest:
    properties:
      ph_no:
        type: string
    required:
    - ph_no
    type: object
  response.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
paths:
  /sendOtp:
    post:
      consumes:
      - application/json
      description: sending otp to the given phone number
      parameters:
      - description: sendOtp
        in: body
        name: sendOtp
        required: true
        schema:
          $ref: '#/definitions/models.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: User Login
      tags:
      - User Authentication
swagger: "2.0"
